### ISSUE TITLE
[Feature] add a AsyncInfiniteScroll component

### ISSUE THREAD

**Issue by tohsaka888** [Apestein/better-react-infinite-scroll#15]
Hi, @Apestein,

better-react-infinite-scroll is a great library that helps in building infinite scrolling components. However, it has some limitations, such as rendering a large number of DOM nodes (e.g., 10,000 items) which can lead to performance issues and even cause the browser to crash.

To address this, I propose building an asynchronous infinite scrolling component that only renders a specified threshold of data (e.g., 100 items). This component will fetch the next page of data from the server when the user scrolls to the top or bottom, thereby achieving true infinite scrolling. Below is my vision for the component:

```tsx
interface AsyncInfiniteScrollProps<T>
  extends React.HTMLAttributes<HTMLDivElement> {
  /**
   * Function to fetch the next page of data.
   * @param lastItem - The last item in the current list.
   * @returns A promise that resolves to an array of items.
   */
  fetchNextPage: (lastItem: T) => Promise<T[]>;

  /**
   * Function to fetch the previous page of data.
   * @param firstItem - The first item in the current list.
   * @returns A promise that resolves to an array of items.
   */
  fetchPreviousPage: (firstItem: T) => Promise<T[]>;

  /**
   * Message to display while loading.
   * @type React.ReactNode
   */
  loadingMessage: React.ReactNode;

  /**
   * Message to display at the end of the list.
   * @type React.ReactNode
   */
  endingMessage: React.ReactNode;

  /**
   * Initial data to display.
   * @type T[]
   */
  initialData: T[];

  /**
   * Number of items to keep in the rendered list.
   * @type number
   * @default 100
   */
  threshold?: number;

  /**
   * Function to render each item.
   * @param item - The item to render.
   * @returns A React node.
   */
  renderItem: (item: T) => React.ReactNode;

  /**
   * Function to generate a unique key for each item.
   * @param item - The item to generate a key for.
   * @returns A unique string key.
   */
  renderKey: (item: T) => string;
}
```

**Comment by tohsaka888** [comment]
[Here is a Demo](https://codesandbox.io/p/devbox/dank-frost-g3j4fs?file=%2Fpackage%2FAsyncInfiniteScroller.tsx%3A147%2C40)

**Comment by Apestein** [comment]
> [Here is a Demo](https://codesandbox.io/p/devbox/dank-frost-g3j4fs?file=%2Fpackage%2FAsyncInfiniteScroller.tsx%3A147%2C40)

I see. So it's like discord's infinite scroll feature. I've been traveling and haven't coded in a while. Will look at this when I can. Didn't think this package would get any attention at all, thanks for contributing.

**Comment by Apestein** [comment]
> [Here is a Demo](https://codesandbox.io/p/devbox/dank-frost-g3j4fs?file=%2Fpackage%2FAsyncInfiniteScroller.tsx%3A147%2C40)

Thanks for your suggestion. I was able to greatly improve this project.
[demo](https://stackblitz.com/~/github.com/Apestein/better-react-infinite-scroll)
